### ISSUE TITLE
The code pulls an error page from instagram instead of json data

### ISSUE THREAD

**Issue by d-packs** [tdrayson/TCT-Instagram-Feed#2]
![sc-210518-222421](https://user-images.githubusercontent.com/33980111/118711124-e16a2f80-b827-11eb-88a9-e42521350298.png)

**Comment by tdrayson** [comment]
This code doesn't currently work. There is a note in the README

I believe it is a CORS issue and I don't think there is anyway to get around it.

The only way I can think is using a Proxy. However, I don't currently have the time to look into it.

**Comment by d-packs** [comment]
I just checked the returned HTML from instagram. It's the html code for the login page. 

![sc-210518-223634](https://user-images.githubusercontent.com/33980111/118712489-86393c80-b829-11eb-953c-a1766ab860af.png)

I presume they have blocked the unauthenticated access to this method of getting resources. Not sure there is a workaround except to go through their API (and create a facebook app on your facebook developer account)

**Comment by tdrayson** [comment]
Instagram seem to change it fairly often. When looking at past threads from forums. It has stopped working multiple times and then randomly started working again.

Instagram just seem to do what they want haha 🤣
